project:
  type: website
  output-dir: docs

website:
  description: "Sitio web de la comunidad de usuarias y usuarios de R en Santiago de Chile"
  site-url: https://santiagoRusers.github.io
  title: "Grupo de usuari@s de R: Santiago"
  navbar:
    right:
      # - text: Introducción
      #   href: introduccion.qmd
      - text: Blog
        href: index.qmd
      - about.qmd
      - icon: github
        href: https://github.com/santiagoRusers
      - icon: linkedin
        href: https://www.linkedin.com/company/santiagorusers
      - icon: twitter
        href: https://twitter.com/santiagoRusers
format:
  html:
    lang: "es"
    theme: [litera, brand, styles.scss]
    mainfont: "Livvic"



