project:
  type: website
  output-dir: docs

website:
  description: "Sitio web de la comunidad de usuarias y usuarios de R en Santiago de Chile"
  site-url: https://santiagoRusers.github.io
  title: "Grupo de usuari@s de R: Santiago"
  favicon: profile.jpg
  open-graph: true
  twitter-card: true
  navbar:
    right:
      - text: <strong>Participa</strong>
        href: participa.qmd
      - text: Blog
        href: index.qmd
      - text: Acerca de
        href: about.qmd
      - icon: github
        href: https://github.com/santiagoRusers
      - icon: linkedin
        href: https://www.linkedin.com/company/santiagorusers
      - icon: twitter
        href: https://twitter.com/santiagoRusers
  announcement: 
    icon: exclamation-circle-fill
    dismissable: true
    content: "[**Inscríbete** a la primera junta del grupo!](participa.html) 18/03/2026"
    type: primary
    position: below-navbar
format:
  html:
    lang: "es"
    theme: [litera, brand, styles.scss]
    mainfont: "Livvic"



